services:
  db:
    image: postgres:15-alpine
    container_name: manga_db
    restart: always
    environment:
      POSTGRES_USER: manga_user
      POSTGRES_PASSWORD: manga_password
      POSTGRES_DB: manga_db
    ports:
      - "127.0.0.1:5454:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: